repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus-stack
    namespace: observability
    chart: prometheus-community/kube-prometheus-stack
    version: 81.4.2
    values:
      - values/prometheus-stack.yaml

  - name: addons
    namespace: observability
    chart: ./addons
    values:
      - values/addons.yaml
    needs:
      - observability/prometheus-stack
