apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-datasource
spec:
  datasource:
    name: prometheus
    type: prometheus
    uid: prometheus
    url: {{ .Values.datasources.prometheus.url }}
    access: proxy
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 30s
  instanceSelector:
    matchLabels:
      dashboard: grafana
