apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{- include "prometheus.name" . | indent 1 }}
subjects:
  - kind: ServiceAccount
    name: {{- include "prometheus.name" . | indent 1 }}
    namespace: istio-system
roleRef:
  kind: ClusterRole
  name: {{- include "prometheus.name" . | indent 1 }}
  apiGroup: rbac.authorization.k8s.io
