apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboard: grafana
spec:
  config:
    global:
      app_mode: development
    auth:
      disable_login_form: "false"
    log:
      mode: console
    security:
      admin_user: admin
      admin_password: start
