keycloakName: lomeone-keycloak
hostName: keycloak.lomeone.com
httpRoute:
  gatewayName: external-gateway
resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    memory: 1Gi
database:
  hostname: db.dptegguvqxbrochgrzla.supabase.co
  port: 5432
externalSecrets:
  dbSecret:
    secretsManagerName: keycloak-db-credentials
