keycloakName: lomeone-keycloak
hostName: keycloak.lomeone.com
httpRoute:
  gatewayName: external-gateway
resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    memory: 1Gi
database:
  hostname: aws-1-ap-northeast-2.pooler.supabase.com
  port: 6543
externalSecrets:
  dbSecret:
    secretsManagerName: keycloak-db-credentials
