keycloakName: lomeone-keycloak
hostName: keycloak.lomeone.com
httpRoute:
  gatewayName: external-gateway
resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    memory: 1Gi
externalSecrets:
  dbSecret:
    secretsManagerName: lomeone-keycloak-db-secret
